language: node_js

node_js: 11

cache: npm

branches:
  only:
    - master # build master branch only

script:
  - hexo generate # generate static files


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: ./dist/
  on:
    branch: master